name: Check OSS licenses compliance

on: push


jobs:
  licenses:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
      - name: Install license checker
        run: go install github.com/google/go-licenses@latest
      - name: Install dependencies
        run: npm install
      - name: Run the tests
        run: npm test
      - name: Build
        run: npm run build